### ISSUE TITLE
请问有相关理论公式吗？

### ISSUE THREAD

**Issue by Soengmou** [sean0921/timeseries_process#3]
你好！请问有相关理论公式吗？或者相关文献方便提供一下吗？

**Comment by sean0921** [comment]
主要是參考這兩個：
* Wdowinski, S., Bock, Y., Zhang, J., Fang, P., and Genrich, J. ( 1997), Southern California permanent GPS geodetic array: Spatial filtering of daily positions for estimating coseismic and postseismic displacements induced by the 1992 Landers earthquake, J. Geophys. Res., 102( B8), 18057– 18070, doi:10.1029/97JB01378.
* Nikolaidis, Rosanne. (2002). Observation of Geodetic and Seismic Deformation with the Global Positioning System. 

其他細節與程式授權仍有待與前輩、作者們確認

**Comment by Soengmou** [comment]
感谢。

**Comment by Soengmou** [comment]
有算例方便提供吗？

**Comment by sean0921** [comment]
整理好相關資料再 reopen
